### ISSUE TITLE
Detect v2 vs v3 APIs and parse correctly

### ISSUE THREAD

**Issue by davesag** [davesag/swagger-routes-express#18]
See the following articles on the V3 format

* https://swagger.io/blog/news/whats-new-in-openapi-3-0/
* https://blog.runscope.com/posts/tutorial-upgrading-swagger-2-api-definition-to-openapi-3
* https://blog.restcase.com/6-most-significant-changes-in-oas-3-0/

**Comment by davesag** [comment]
## Regarding `basePath` vs default `servers` and path specific `servers`

In Swagger v2 they have the concept of a `basePath` which gets appended to the start of every subsequent path. In order to allow for some flexibility with this we check each path for a "root" `tag`.  If a path is tagged with "root" then we don't include the `basePath` in the route.

OpenAPI 3 offers a lot more flexibility in that you can define simple, and complex, `servers`, either globally (in which case they become the default for a path)

### Simple Servers

Servers, whether global or path specific can be defined minimally via

```
servers:
  - url: '/some/base/path'
```

We will treat such urls in the same way we treat the `basePath` in v2, with servers defined in the a path overriding the global definitions.

If there is more than one server defined, we'll pick the first one that is a simple relative path.

### Complex Servers

Servers may also be defined with absolute urls, and with template variables, for example

```
servers
  - url: 'https://{host}/api/{version}'
     variables:
        host:
          default: 'www.example.com'
          enum:
            -  'www.example.com'
            - 'www.test.com'
       version:
         default: 'v3'
```

Servers with absolute urls will be considered to be out of scope unless the `ignoreAbsolute` flag is set to true when initialising the router.

You may pass in values for variables when configuring the router.

```
const swaggerRoutes = (api, swaggerDoc, {
  variables: {
    host: 'some.hostname.tes',
    version: 'v3'
  }
})
```

The values will be inserted into the template before any matching happens.
