### ISSUE TITLE
Swagger v2 global security definition

### ISSUE THREAD

**Issue by fstorz** [davesag/swagger-routes-express#63]
On the readme there is a section regarding global security definition, but only in the context of OpenAPI v3. The global definition of security blocks should be also able for Swagger v2

> OpenAPI V3 Security Blocks
OpenAPI V3 allows you to define a global security definition as well as path specific ones. The global security block will be applied if there is no path specific one defined.

I have the following snippet in my swagger.yaml
```
securityDefinitions:
  basicAuth:
    description: Basic authentication with technical user and password.
    type: basic
security:
  - basicAuth: []
```

I added the security method like the following
```
const options = {
    security: {
        basicAuth: basicAuth
    }
};

...
    const connect = connector(api, apiDefinition, options);
...
async function basicAuth(req, res, next) {
    if (await checkAuthHeader(req)) return next();
    return res.status(401).json(unauthorized);
}
```
When a request is sent to the app, the security filter is not evaluated
